messages:
  help: "&7[&3JFKey&7] /jfkey add|clear|reload"
  invalid: "&7[&3JFKey&7] /jfkey add <command>"
  added: "&7[&3JFKey&7] Command added: &f{command}"
  clear: "&7[&3JFKey&7] Command cleared, your last command &f{command}"
  no-command: "&7[&3JFKey&7] &7You haven't set up any command!"
  no-permission: "&7[&3JFKey&7] &cYou do not have permission to use this command!"
  reload: "&7[&3JFKey&7] &aConfig reloaded!"